### ISSUE TITLE
Setting this up to work

### ISSUE THREAD

**Issue by connecteev** [GregBrimble/tailwindui-crawler-action#5]
@GregBrimble this workflow looks amazing, but I'm having trouble setting this up and testing that it works.

- I created a private repo with secrets for TAILWINDUI_EMAIL and TAILWINDUI_PASSWORD
- I also created a .github/workflows/default.yml file based on the example at https://github.com/GregBrimble/tailwindui-crawler-action

```
name: Example/Test
on:
  push:
  schedule:
    - cron: "0 0 * * *" # Every day at midnight

jobs:
  test:
    name: Example/Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run crawler
        uses: gregbrimble/tailwindui-crawler-action@master
        with:
          email: ${{ secrets.TAILWINDUI_EMAIL}}
          password: ${{ secrets.TAILWINDUI_PASSWORD }}
```
- I then set up github notifications for my private repository.

At no time did I clone https://github.com/GregBrimble/tailwindui-crawler-action or https://github.com/kiliman/tailwindui-crawler/

Am I missing a step? Thank you!

**Comment by GregBrimble** [comment]
Hi @connecteev !

Thanks for trying this out :) Sorry it isn't working for you straightaway.

Have you first tried the example config in the README.md?

```yml
# .github/workflows/default.yml

name: Update
on:
  schedule:
    - cron: "0 0 * * *" # Every day at midnight

jobs:
  update:
    name: Update
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run crawler
        uses: gregbrimble/tailwindui-crawler-action@v1.0.0
        with:
          email: ${{ secrets.TAILWINDUI_EMAIL }}
          password: ${{ secrets.TAILWINDUI_PASSWORD }}
```

This obviously schedules this to be run every day at midnight, so feel free to adjust the cron schedule so you can more test it more rapidly.

Setting up the secrets sounds good, and notifications sound fine. And you shouldn't need to clone either repo, since this happens in the Action.

Do you have any errors appearing in the Action logs?

If possible, please provide a screenshot/copy-paste of those logs, and of your yml file configuration, and I can dig into this for you :)
